name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    # Make sure Python searches the repo root for modules
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v3

      - name: List workspace files
        run: ls -R .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest -q
