name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest -q

      - name: Build Docker image
        run: docker build -t ci-cd-demo:\${{ github.sha }} .

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
            | sh -s -- -b /usr/local/bin

      - name: Scan image with Trivy
        run: |
          trivy image \
            --exit-code 1 \
            --severity HIGH,CRITICAL \
            --format table \
            ci-cd-demo:\${{ github.sha }}

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}

      - name: Tag & push image
        run: |
          docker tag ci-cd-demo:\${{ github.sha }} ghcr.io/\${{ github.repository }}:latest
          docker push ghcr.io/\${{ github.repository }}:latest
